# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # ##########.#
  # Bootloader.#
  # ##########.#

  boot.loader.systemd-boot.enable = true;
  boot.loader.systemd-boot.configurationLimit = 5; # Limit the amount of configurations
  boot.loader.efi.canTouchEfiVariables = false;

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.kernelPackages = pkgs.linuxPackages_latest;

  # ########## #
  # Partitions #
  # ########## #

  boot.initrd.luks.devices.root = {
    device = "/dev/disk/by-label/NIXLUKS";
    preLVM = true;
  };

  fileSystems."/" =
    { device = "/dev/disk/by-label/NIXROOT";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/NIXBOOT";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/503740f9-fe89-4463-b675-ebb5a6117b9c"; }
    ];

  # ######## #
  # Firmware #
  # ######## #

  hardware.enableRedistributableFirmware = lib.mkDefault true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  services.fwupd.enable = true; # auto firmware updater

  # ######### #
  # Bluetooth #
  # ######### #

  hardware.bluetooth.enable = true;
  services.blueman.enable = true;

  # ############ #
  # Architecture #
  # ############ #

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  # ###### #
  # Laptop #
  # ###### #

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

}
